### PR TITLE
More User Ram

### PR DESCRIPTION
**Pull request by kueken**
Try Build with more free User-ram.

### CODE REVIEW

**Comment by Taapat** [comment]
Sorry, maybe I'm wrong, but the 32Mb bigphysarea and 96MB LMI_IO are necessary to use the PIP.
Therefore I can not accept this.

**Comment by kueken** [comment]
Ok.
No Problem. 
Has not been tested with PIP, sorry. 
I have always disabled this feature 
You can try it locally, if you want.
So it was simply an info.

By

**Comment by Taapat** [comment]
I am a long time ago changed this to use PIP: https://bitbucket.org/Taapat/tdt-arp-taapat/commits/5986b450d301af42783950071f4e89762230c8f3
Only I'm not sure is it really necessary to increase both- bigphysarea and LMI_IO.

If you have time to test it, I will be happy to add the changes which do not affect the PIP.
If you're testing remember that PIP do not work on HD channels.

**Comment by kueken** [comment]
`
root@spark:~# cat /proc/bpa2
Partition: 'bigphysarea'
Size: 32768 kB, base address: 0x48000000
Statistics:                  free           used
- number of blocks:             3             11
- size of largest block:    11024 kB       16384 kB
- total:                    11280 kB       21488 kB
Allocations:
- 98304 B at 0x493b2000
- 98304 B at 0x4939a000
- 770048 B at 0x49480000
- 524288 B at 0x49400000
- 16777216 B at 0x48390000
- 196608 B at 0x48360000
- 196608 B at 0x48330000
- 196608 B at 0x48300000
- 1048576 B at 0x48200000
- 1048576 B at 0x48100000
- 1048576 B at 0x48000000

Partition: 'LMI_IO' aka 'audio' aka 'v4l2-coded-video-buf' aka 'BPA2_Region1' aka 'v4l2-video-buffers' aka 'coredisplay-video' aka 'gfx-memory' aka 'BPA2_Region0' aka 'LMI_VID'
Size: 98304 kB, base address: 0x4a000000
Statistics:                  free           used
- number of blocks:             1              9
- size of largest block:    13716 kB       36864 kB
- total:                    13716 kB       84588 kB
Allocations:
- 36864 B at 0x4d992000
- 36864 B at 0x4d989000
- 36864 B at 0x4d980000
- 37748736 B at 0x4b580000
- 16777216 B at 0x4a580000
- 1572864 B at 0x4a400000
- 4194304 B at 0x4a000000
- 9437184 B at 0x4e99b000
- 16777216 B at 0x4d99b000

root@spark:~#
`
This was Memory free with your Image with PIP in function on 2 SD-programs.
More User-Ram is possible, but not my Idea.

You,re right.
Sorry

**Pull request closed without merging**
